### ISSUE TITLE
Rename repo from ocitools to runtime-tools

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/runtime-tools#205]
After the TOB finishes voting, we will do a repo rename here to "runtime-tools"
https://groups.google.com/a/opencontainers.org/forum/#!forum/tob

This is based on the new OCI Tooling project proposal:
https://github.com/opencontainers/tob/blob/master/proposals/tools.md

**Comment by caniszczyk** [comment]
FYI @mrunalp and @liangchenye, let me know if you have any questions

**Comment by mrunalp** [comment]
@caniszczyk We will need to make some changes to the code so that it continues to compile but I can do that after the rename.

**Comment by wking** [comment]
On Thu, Sep 08, 2016 at 02:28:36PM -0700, Mrunal Patel wrote:
> @caniszczyk We will need to make some changes to the code so that it
> continues to compile but I can do that after the rename.

GitHub (usually? always? for some time period?) redirects renamed
repositories.  So things might still compile after the rename.

But I agree that we'll want a general update from ocitools →
oci-runtime-tools or some such to match the rename.

**Comment by liangchenye** [comment]
@caniszczyk No extra question.

@mrunalp  @wking I think we need to change 'Readme' to make it OCI style, add `code of conduct` for example.

**Comment by wking** [comment]
On Thu, Sep 08, 2016 at 05:56:22PM -0700, 梁辰晔 (Liang Chenye) wrote:
> I think we need to change 'Readme' to make it OCI style, add `code
> of conduct` for example.

That sounds good to me.  Keeping all that in sync per-project is
tedious, so I've pushed opencontainers/project-template#20 to collect
all the cross-project boilerplate in one place.  If we can land that
in project-template, we can run:

  $ git pull --log git://github.com/opencontainers/project-template.git
  $ git checkout --theirs CONTRIBUTING.md LICENSE MAINTAINERS_GUIDE.md
  $ git checkout --ours MAINTAINERS README.md
  $ emacs .pullapprove.yml  # adjust reviewers.teams
  $ git add .pullapprove.yml CONTRIBUTING.md LICENSE MAINTAINERS MAINTAINERS_GUIDE.md README.md
  $ git commit

To test it out locally, you can replace the first line with:

  $ git pull --log git://github.com/wking/oci-project-template.git generic-docs

**Comment by caniszczyk** [comment]
TOB vote passed here so I did the rename:

https://github.com/opencontainers/runtime-tools
