### ISSUE TITLE
bump runtime-spec

### ISSUE THREAD

**Issue by runcom** [opencontainers/runtime-tools#217]
current master isn't working with runtime-spec@rc1 nor rc2 - generate above all should be updated

**Comment by wking** [comment]
I'd guess the plan would be something like:

1. Land #181 or forward-port #161 and #202 to master.
2. Delete the v1.0.0.rc1 branch, closing outstanding v1.0.0.rc1
   backport PRs.
3. Bump the runtime-spec dependency to
   opencontainers/runtime-spec@7dab1a245d.
4. Create a v1.0.0.rc2 branch.

**Comment by liangchenye** [comment]
already updated to rc5, close.
