### ISSUE TITLE
Using cobra instead of cli

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [opencontainers/runtime-tools#222]
Just wanted to know, if there is any specific reason for cli instead of cobra as we can reduce some of the code in generate.go using cobra. Something like 

if context.IsSet("read-only") {
        g.SetRootReadonly(context.Bool("read-only"))
}

could be set as :
cmd.Flags().BoolVar(&context.readonly, "read-only", context.readonly "make the container's rootfs read-only.")
where cmd here points to oci-runtime-tool generate

I may be missing an obvious point here as I am new to code base. Please, feel free to correct me in case I made some mistake.

**Comment by GrantSeltzer** [comment]
urfave/cli is used in most oci cli projects (this, runc, cri-o, etc...). Cobra definitely is more popular but I don't see any technical reason to switch over.

**Comment by wking** [comment]
image-tools had been using cobra, but switched to urfave/cli in opencontainers/image-tools#103.  I agree with @GrantSeltzer about not seeing a reason to switch.

**Comment by ravisantoshgudimetla** [comment]
@GrantSeltzer @wking  - if so, I am closing this off.
