### ISSUE TITLE
container does not  exist when I run test_runtime.sh

### ISSUE THREAD

**Issue by heartlock** [opencontainers/runtime-tools#228]
container "7df3579a-af8b-402f-b8d3-bc502521841d" does not exist
Runtime runc failed validation

I think we should create container first before start it.
https://github.com/opencontainers/runtime-tools/blob/master/test_runtime.sh#L82

**Comment by mrunalp** [comment]
This is an issue because we are using start in test_runtime.sh
Try replacing `start` -> `runc`.

**Comment by heartlock** [comment]
@mrunalp it works, and I make a pr to fix this issue #232

**Comment by mrunalp** [comment]
@heartlock We need a wrapper process like discussed in #232

**Comment by liangchenye** [comment]
fixed. close
