### ISSUE TITLE
Go getting opencontainers/runtime-tools/generate is impossible

### ISSUE THREAD

**Issue by papey** [opencontainers/runtime-tools#229]
Hi,

I can't go get opencontainers/runtime-tools/generate.

```
go get github.com/opencontainers/runtime-tools/generate

# github.com/opencontainers/runtime-tools/generate
$GOPATH/src/github.com/opencontainers/runtime-tools/generate/generate.go:67: undefined: specs.Rlimit
$GOPATH/src/github.com/opencontainers/runtime-tools/generate/generate.go:115: undefined: specs.Resources
$GOPATH/src/github.com/opencontainers/runtime-tools/generate/generate.go:123: undefined: specs.Namespace
$GOPATH/src/github.com/opencontainers/runtime-tools/generate/generate.go:140: undefined: specs.Device
$GOPATH/src/github.com/opencontainers/runtime-tools/generate/generate.go:487: undefined: specs.Action
$GOPATH/src/github.com/opencontainers/runtime-tools/generate/generate.go:591: undefined: specs.Syscall
$GOPATH/src/github.com/opencontainers/runtime-tools/generate/generate.go:594: undefined: specs.Syscall
$GOPATH/src/github.com/opencontainers/runtime-tools/generate/generate.go:598: undefined: specs.Syscall
$GOPATH/src/github.com/opencontainers/runtime-tools/generate/generate.go:996: undefined: specs.Namespace
$GOPATH/src/github.com/opencontainers/runtime-tools/generate/generate.go:1067: undefined: specs.Arg
$GOPATH/src/github.com/opencontainers/runtime-tools/generate/generate.go:598: too many errors 
```
Is this error due to some Godeps/vendoring mismatch regarding runtime-spec ?

**Comment by papey** [comment]
Aww, ok. Regarding the current version of runtime-spec, specs fields are now prefixed by "Windows" or "Linux"

**Comment by wking** [comment]
On Tue, Oct 04, 2016 at 07:35:58AM -0700, Wilfried OLLIVIER wrote:
> Regarding the current version of runtime-spec, specs fields are now
> prefixed by "Windows" or "Linux"

This was opencontainers/runtime-spec#567.  runtime-tools pins its
dependencies, so being 'go get'-able is not a high priority.  Folks
who want a binary should build it via ‘make’ (which sets up a GOPATH
to use the pinned dependencies).  Folks who want the libraries should
pin runtime-tools to a specific version, and also pin its dependencies
to the versions pinned by their chosen runtime-tools (although you can
probably adjust the dependency versions somewhat if you're willing to
keep the pieces ;).

There's also the 1.0.0.rc1 branch (built against an official
runtime-tools release).  If I was including runtime-spec as a
dependency, I'd stick to branches like that (vs. master, which pins a
mostly-arbitrary runtime-spec release).  More on this versioning in
#108 and #140.

**Comment by papey** [comment]
Ok, that's clear, thanks.
