### ISSUE TITLE
update to runtime-spec v1.0.0-rc2

### ISSUE THREAD

**Issue by cyphar** [opencontainers/runtime-tools#268]
Currently validation fails against `v1.0.0-rc2` images, which is causing issues for adding `oci-runtime-tools`-based testing for `umoci` (cyphar/umoci#12).

The current error is just for `kernelTCP`, which was fixed in the new version of the spec. The only really annoying part of the update is that you need to handle the namespacing of all of the Go structs (where everything has Linux prepended to it now).

```
# oci-runtime-tool validate --path /tmp/bundle.a (status=1)
# time="2016-11-12T16:04:09Z" level=fatal msg="2 Errors detected:\n'Memory.KernelTCP' should not be empty.\ninternal error: validate currently only handles version 1.0.0-rc1-dev, but the supplied configuration targets 1.0.0-rc2"
```

**Comment by liangchenye** [comment]
close, already updated to rc5.
