### ISSUE TITLE
Support --env-file parameter

### ISSUE THREAD

**Issue by wrouesnel** [opencontainers/runtime-tools#275]
The docker env-file parameter is very useful when running containers under systemd which require some amount of environment setup.

It would be extremely useful (given how runc is used) to be able to use the same parameter in runtime-tools when dynamically generating `config.json` bundles.

**Comment by wking** [comment]
Like jq's --slurpfile:

  $ echo '{}' >config.json  # or however you source your original
  $ cat >env <<EOF
  > A=B
  > C=D
  > EOF
  $ jq --slurpfile env <(sed 's/^\(.*\)$/"\1"/' env) '.process.env= $env' config.json 
  {
    "process": {
      "env": [
        "A=B",
        "C=D"
      ]
    }
  }
