### ISSUE TITLE
Allow specifying mount parameters for --tmpfs ?

### ISSUE THREAD

**Issue by wrouesnel** [opencontainers/runtime-tools#280]
The tmpfs property follows docker by default, which mounts --tmpfs filesystems noexec, nosuid, nodev.

These are not particularly useful defaults in a lot of circumstances (i.e. providing `/tmp` to a container) because a huge amount of software expects to be able to execute things out of such directories.

It would be convenient to support additional syntax which allow being explicit about the mount options to tmpfs - i.e. `--tmpfs /tmp:defaults` or `--tmpfs /tmp:-` for no special options, `--tmpfs /tmp:nosuid` for adding options.

**Comment by Mashimiao** [comment]
Adding options or default options for tmpfs,  are already supported by --tmpfs.
I have pushed a PR #279 to let users add custom additional mounts.  
I think you can add /tmp with on special options by --mounts-add, like --mounts-add tmpfs:/tmp:tmpfs

**Comment by wrouesnel** [comment]
Just tested and found - thanks. This could possible use a hint in the cmdline help.
