### ISSUE TITLE
Older versions of oci-runtime-tool didn't generate the seccomp rules for runc.

### ISSUE THREAD

**Issue by yamen94** [opencontainers/runtime-tools#304]
Is there a newer version cuz when I use criu i got an error with the seccomp

**Comment by GrantSeltzer** [comment]
There's a new version of the seccomp json spec that the generate/seccomp package doesn't yet support, if runc uses that then it would explain the issue. [Here's an example of the new spec.](https://github.com/kubernetes-incubator/cri-o/blob/be32aa566ea4793df7f2ca50de2c36635de3f0cf/seccomp.json)

I'm going to look into changing fixing that.

**Comment by liangchenye** [comment]
The new version will generate 'seccomp' rules for runc. Close.
