### ISSUE TITLE
oci-runtime-tool validate is unable to detect typo like rootPropagation

### ISSUE THREAD

**Issue by qiancai** [opencontainers/runtime-tools#317]
oci-runtime-tool validate is unable to  detect incorrect keywords in config.json before it runs. For example,

"linux": {
    "rootPropagation": "shared"
...

instead of "rootfsPropagation".

**Comment by wking** [comment]
On Wed, Feb 01, 2017 at 02:23:24PM -0800, Qian Cai wrote:
> oci-runtime-tool validate is unable to detect incorrect keywords in
> config.json before it runs. For example,
> 
> "linux": {
>     "rootPropagation": "shared"
> ...
> 
> instead of "rootfsPropagation".

Those typos are valid unknown properties, which the runtime MUST
ignore [1].  However, warning about unknown properties would be nice.

[1]: https://github.com/opencontainers/runtime-spec/blob/v1.0.0-rc3/config.md#extensibility

**Comment by liangchenye** [comment]
Hi, QianCai, I close this according to https://github.com/opencontainers/runtime-spec/blob/v1.0.0-rc3/config.md#extensibility
