### ISSUE TITLE
replace the arguments processor

### ISSUE THREAD

**Issue by Kxuan** [opencontainers/runtime-tools#330]
We now use urfave/cli to process the arguments of process. But there is a problem that urfave/cli do not provide the order of arguments. 

The order is so important in some case. Let's think about such a case:
> The user do not want any default rlimit config, and wants to use his rlimit config. 

In this case, the user needs to remove all default rlimit config, and then adds a rlimit to the config. So the user uses this command:

```bash
oci-runtime-tool generate --rlimits-remove-all --rlimits-add RLIMIT_NOFILE:10:10
```

But the result is not accepable. This command will generate a config file **without any rlimit config**. 

Why it happends?

Because the arguments processor does not provides the order of 'rlimits-remove-all' and 'rlimits-add', we dont know which is the first.
In this time, the oci-runtime-tool process 'rlimits-remove-all' after 'rlimits-add', so it firstly adds a rlimits RLIMITS_NOFILE, then remove all rlimits.

How to fix

I have not found any way to get the order of arguments, so I think replace with a new arguments processor is the only way to solve this problem.

I submit this issue because I dont know which arguments processor we should to use. I think we can discuss about them.

**Comment by tianon** [comment]
Can't we specify a callback for the flag so that we can run some custom
code instead of simply storing it in a variable? (That should ensure we can
clear the setting at the right point during flag processing if so.)

**Comment by Mashimiao** [comment]
in which order to deal with flags, it's not the business of argument processor.
I believe there are not any one can handle this.
And remove-all and limits-add  conflict, maybe we should clearly tell user this.
If we really want to support remove-all and limits-add work together, I think remove-all should work first.  And it becomes a problem how we design the logic

**Comment by Kxuan** [comment]
@Mashimiao In C, getopt() can be used to process arguments in order. Maybe there are some methods in Go, which can process the arguments like getopt().

**Comment by Kxuan** [comment]
@tianon That may be a solution. But it seems that urfave/cli doest support callback. Should we do it by ourselves?
