### ISSUE TITLE
setup milestones

### ISSUE THREAD

**Issue by Mashimiao** [opencontainers/runtime-tools#343]
we should setup milestones for runtime-tools. 
I want to create one milestone for v1.0.0.
The question is we should set due date to when is suitable.  @opencontainers/runtime-tools-maintainers

**Comment by wking** [comment]
> The question is we should set due date to when is suitable.

I wouldn't bother with due dates, just cut a release when you clear out all the issues (assuming you're up to date on triage).  If somebody is getting paid to hit a target by a certain time, due dates make sense, but I don't think that's the case for the OCI.

**Comment by Mashimiao** [comment]
Though we don't get paid, at least as runtime-tools maintainers, it's our responsibility to maintain it and lead it to be ready as soon as possible.
My own opinion, I think the development of runtime-tools is  a little slow, may be because we are lack of goals to make effort.
So, I think we'd better set a milestone, it's not only a restriction but also a clear target for us.

**Comment by wking** [comment]
On Wed, Mar 08, 2017 at 10:05:29PM -0800, Ma Shimiao wrote:
> My own opinion, I think the development of runtime-tools is a little
> slow, may be because we are lack of goals to make effort.  So, I
> think we'd better set a milestone, it's not only a restriction but
> also a clear target for us.

I don't think putting a date on milestones will help anyone work
harder.  In the spec repos, the only currently open milestone with a
due date is [1], it's currently 6 days over, and I don't expect
runtime-spec to be cutting 1.0 in the next few weeks either.  But if
you do think that putting a date on milestones will help motivate
runtime-tools maintainers, then I guess assign some dates ;).

[1]: https://github.com/opencontainers/runtime-spec/milestone/7

**Comment by Mashimiao** [comment]
A successful project need efforts from every contributor.  I want to get opinions from other maintainers. @opencontainers/runtime-tools-maintainers 
How should we set milestone or just think it makes no sense as @wking ?

**Comment by vbatts** [comment]
@Mashimiao I think it is fine to set reasonable goals on the time of the milestone, though for the *-spec repos, those times were constantly being changed. Perhaps, come up with a reasonable schedule for milestones and target dates, then send it to the dev@ list to socialize it. With this approach, hopefully the dates will be more concrete than the *-spec dates we had set. :-)

**Comment by Kxuan** [comment]
I think we need to review all arguments. The arguments make people so confused at this moment.

For example, "oom-score-adj" and "linux-cpu-shares" are both linux specified arguments, but "linux-cpu-shares" have the "linux" prefix and "oom-score-adj" haven't.

I think this is the last chance we change these arguments. After  1.0.0 released, we can not change the argument's name easily.

**Comment by crosbymichael** [comment]
@Kxuan yes, we need to take a final pass through and review for consistency of the fields and options so we don't have these mistakes in the final.

**Comment by wking** [comment]
Obsoleted by #465?  I don't mind which issue stays open (if we want to [keep one open for milestone discussion][1]), but I don't think we need *two* open issues for generic milestone discussion ;).

[1]: https://github.com/opencontainers/runtime-tools/issues/465#issuecomment-329972075
