### ISSUE TITLE
generate errors out if an action is specified that's the same as default

### ISSUE THREAD

**Issue by GrantSeltzer** [opencontainers/runtime-tools#395]
For example:

 ```
17:33:40 grant in ~> ~ 
[*] oci-runtime-tool generate  --seccomp-default trace --seccomp-trace clone
default action already set as SCMP_ACT_TRACE
```

Instead, the default should be set to the specified action and a new rule just shouldn't be added specifically for the syscall... then the config should be printed as normal.

Other conflicting rules are just taken into account and generated gracefully.  [This](https://github.com/GrantSeltzer/Manhattan/blob/master/resources/Logic.png) doc explains the logic. That should probably be moved over to this repo as well.

**Comment by Mashimiao** [comment]
That' really a problem, we also have seccomp problem in default template. Maybe we can fix it after solve simple template problem #379
