### ISSUE TITLE
validate config.json by https://github.com/opencontainers/runtime-spec/tree/master/schema 

### ISSUE THREAD

**Issue by liangchenye** [opencontainers/runtime-tools#453]
https://github.com/opencontainers/runtime-spec/tree/master/schema has strong and beautiful validation function. We can use it here.

**Comment by wking** [comment]
Dup of #197?

**Comment by Mashimiao** [comment]
@liangchenye  as #374 merged, can we close this issue?

**Comment by liangchenye** [comment]
close
