### ISSUE TITLE
specerror: Strings contain Markdown links

### ISSUE THREAD

**Issue by wking** [opencontainers/runtime-tools#496]
We [currently have error strings like][1]:

    **`ociVersion`** (string, Required) MUST be in [SemVer v2.0.0][semver-v2.0.0] format and specifies the version of the Open Container Initiative Runtime Specification with which the bundle complies.

while I am in favor of including the spec requirement, and in favor of auto-generating those strings by scraping the spec, I'd rather strip any Markdown out and instead be using:

    ociVersion (string, Required) MUST be in SemVer v2.0.0 format and specifies the version of the Open Container Initiative Runtime Specification with which the bundle complies.

[1]: https://github.com/opencontainers/runtime-tools/blob/6554addc535ff61f02ce943e1a048148944be497/specerror/config.go#L12

**Comment by wking** [comment]
Also, upstream has [`REQUIRED`][1], so I'm not sure why our local line has `Required`.

[1]: https://github.com/opencontainers/runtime-spec/blame/v1.0.0/config.md#L17

**Comment by liangchenye** [comment]
I'll change `** **` to `ociVersion`, it looks better. And the tool will also be updated.

**Comment by liangchenye** [comment]
@wking `Required` is my tricky replacement in my tool. Since all the `(, REQUIRED)` will be done by `CheckJSONSchema`, I simply exclude all these RFC errors.

**Comment by liangchenye** [comment]
Some sentences is end with "following format|pattern|ABC ." , I change them to 'default format|pattern|ABC.".

**Comment by liangchenye** [comment]
I think we can close this since
1. we are using spec error code with `int` type
2. the markdown links are removed from the annotations of the spec error code
