### ISSUE TITLE
Inconsistency between "ocitools generate" and "runc spec"

### ISSUE THREAD

**Issue by amitsaha** [opencontainers/runtime-tools#51]
I have seen the following inconsistencies between "ocitools generate" and "runc spec". So far:

**terminal**

`runc spec` defaults `terminal` to `true`, but `ocitools` defaults to `false`. I also think it should allow setting the terminal attribute.

**rootfs readonly**

`ocitools generate` defaults to `true` wheras `runc spec` defauilts to  `false`

I will update this list, but for now here is an example generated by each tool: https://gist.github.com/amitsaha/3fed080c8f2de6f52082ce84e82656de

**Comment by liangchenye** [comment]
Hi @amitsaha , thanks for the report.

The `default terminal` is `false` in `runtime spec` now.
https://github.com/opencontainers/runtime-spec/blob/master/config.md#process-configuration

The `default readonly` in `ocitool generate` is also `false` now.
https://github.com/opencontainers/ocitools/blob/master/generate.go#L721

**Comment by liangchenye** [comment]
close
