### ISSUE TITLE
start validation test panics if process was not set

### ISSUE THREAD

**Issue by dongsupark** [opencontainers/runtime-tools#617]
https://github.com/opencontainers/runtime-tools/pull/578 introduced a new test for [StartWithProcUnsetGenError](https://github.com/opencontainers/runtime-spec/blob/master/runtime.md#start), which is checked by [validation/start.go](https://github.com/opencontainers/runtime-tools/blob/master/validation/start.go#L93..L111). However, when testing with runc, the test fails because `Create()` returns `exit status 2`. It turns out, that's because [`validateProcessSpec()` in runc panics with nil-dereference](https://github.com/opencontainers/runc/blob/v1.0.0-rc5/utils_linux.go#L366..L377) when its input `spec` (type of *Process) is nil.

From my understanding, the original idea of the test was probably not to test whether `spec.Process` is nil or not. It should actually test if [`process` in config.json](https://github.com/opencontainers/runtime-spec/blob/master/config.md#process) is valid. So I think we should actually decode a config json file to see if it has a valid `process` entry.

/cc @liangchenye

**Comment by wking** [comment]
> It turns out, that's because validateProcessSpec() in runc panics with nil-dereference when its input `spec` (type of *Process) is nil.

I have a patch in flight for this with opencontainers/runc#1726.

**Comment by wking** [comment]
> From my understanding, the original idea of the test was probably not to test whether `spec.Process` is nil or not. It should actually test if process in config.json is valid.

From runtime-spec, you should be able to `create` but not `start` a container with an unset `process` (more background on that in opencontainers/runtime-spec#701).  The purpose of the `StartWithProcUnsetGenError` test is to exercise that usecase and ensure that `create` works (as the spec expects) and the `start` fails (as the spec requires).

**Comment by dongsupark** [comment]
@wking Thanks.
I hope https://github.com/opencontainers/runc/pull/1726 could be merged.
