### ISSUE TITLE
Configuring IP address and mapped ports

### ISSUE THREAD

**Issue by washraf** [opencontainers/runtime-tools#62]
How to use the tool to configure the IP address, and exported ports or a runc container ?

**Comment by amitsaha** [comment]
`ocitool` allows you to define hooks. For a default bridge networking setup, you have to define a `prestart` hook to run [netns](https://github.com/jfrazelle/netns) which should be like:

```
  "hooks": {
                "prestart": [
                        {
                                "path": "<go-path>/bin/netns"
                        }
                ]
        },
```
From what I have seen so far, you don't have to explicitly define any exported ports. If you run a server in your container, it should be accessible from `<container-ip>:port` from your host.

**Comment by wking** [comment]
On Mon, May 09, 2016 at 07:09:03PM -0700, Amit Saha wrote:
> From what I have seen so far, you don't have to explicitly define
> any exported ports.

Libnetwork (used by both netns and docker/docker) can set up per-port
forwarding using iptables, but it doesn't look like netns exposes that
functionlity (yet?).

**Comment by amitsaha** [comment]
That is a good point @wking

**Comment by washraf** [comment]
@amitsaha @wking  check this out 
https://github.com/xemul/criu/issues/165

**Comment by Mashimiao** [comment]
closing as issues has been solved
