### ISSUE TITLE
:rotating_light: Overhaul CI steps

### ISSUE THREAD

**Issue by vbatts** [opencontainers/runtime-tools#726]
* [x] remove travis (it is now defunct and blocking merges)
* [x] switch to github actions
* [x] switch to Github CODEOWNERS
* [x] remove pullapprove

**Comment by kolyshkin** [comment]
I have removed pullapprove integration, instead enabling master branch protection rules (two LGTMs from maintainers are required to merge a PR, no direct pushes are allowed, etc).

@vbatts can you please elaborate on CODEOWNERS? As per my older comment,

>  I read https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners but I don't quite get the benefits of using CODEOWNERS.

**Comment by vbatts** [comment]
whoa sorry (since October 😓 )
CODEOWNERS is being used to migrate off of pullapprove (and whatever), to use the built in github approval configuration
