### ISSUE TITLE
New Maintainers on this Repo

### ISSUE THREAD

**Issue by rhatdan** [opencontainers/runtime-tools#734]
Can we get newer maintainers and committers on this Repo.  The github.com/containers project is relying on this repo (Podman, Buildah, CRI-O) while some other repos like containerd have moved on.  This has caused some PRs to lanquish, since the some of the maintainers are not working with this library. 
I would like to see if we could add someone like @kolyshkin or @vrothberg as a core maintainer and then help get some PRs and issues resolved.

**Comment by kolyshkin** [comment]
Fixed by #736

@vrothberg if you plan to become a maintainer for repo, feel free to start contributing.
